apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
data:
  udrcfg.yaml: "info:\n  version: 1.0.1\n  description: UDR initial local configuration\n  #magic___^_^___line\nconfiguration:\n  sbi:\n    scheme: http\n    registerIPv4: udr-nudr # IP used to register to NRF\n    bindingIPv4: 0.0.0.0  # IP used to bind the service\n    port: 80\n    tls:\n      key: config/TLS/udr.key\n      pem: config/TLS/udr.pem\n      #magic___^_^___line\n  mongodb:\n    name: free5gc\n    url: mongodb://mongodb:27017       \n      #magic___^_^___line\n  nrfUri: http://nrf-nnrf:8000\n      #magic___^_^___line\nlogger:\n  MongoDBLibrary:\n    ReportCaller: false\n    debugLevel: info\n  OpenApi:\n    ReportCaller: false\n    debugLevel: info\n  PathUtil:\n    ReportCaller: false\n    debugLevel: info\n  UDR:\n    ReportCaller: false\n    debugLevel: info\n"
